-- V1: settlement_db 베이스라인 (ADR 0020 Phase 4)
--
-- settlement-service 가 소유하는 전체 스키마. JPA 엔티티를 단일 진실원천으로 Hibernate
-- schema-generation 으로 생성한 DDL 을 베이스라인화했다(SettlementDbBootIT 가 원천 DDL 을 export).
-- opslab 의 24개 마이그레이션(14 CREATE + 10 ALTER) 누적 결과와 동일한 최종 스키마다.
--
-- ★ 교차 도메인 FK 없음: settlement 엔티티는 order(payments/orders/users/products)·refund 를
--   ID(Long)로만 참조하므로 Hibernate 가 외래키를 만들지 않는다 → cross-DB 의존 0, 물리 분리 안전.
--   내부 참조(settlement_adjustments→settlements 등)도 애플리케이션 레벨로 보장한다.

CREATE TABLE IF NOT EXISTS public.settlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL,
    order_id bigint NOT NULL,
    payment_amount numeric(10,2) NOT NULL,
    refunded_amount numeric(10,2) NOT NULL,
    commission numeric(10,2) NOT NULL,
    commission_rate numeric(5,4) NOT NULL,
    net_amount numeric(10,2) NOT NULL,
    holdback_amount numeric(12,2) NOT NULL,
    holdback_rate numeric(5,4) NOT NULL,
    holdback_release_date date,
    holdback_released boolean NOT NULL,
    holdback_released_at timestamp(6),
    settlement_date date NOT NULL,
    status varchar(20) NOT NULL,
    failure_reason varchar(255),
    confirmed_at timestamp(6),
    version bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uk_settlements_payment_id UNIQUE (payment_id)
);
CREATE INDEX IF NOT EXISTS idx_settlements_status ON public.settlements (status);
CREATE INDEX IF NOT EXISTS idx_settlements_settlement_date ON public.settlements (settlement_date);

CREATE TABLE IF NOT EXISTS public.settlement_adjustments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint NOT NULL,
    refund_id bigint,
    chargeback_id bigint,
    amount numeric(10,2) NOT NULL,
    status varchar(20) NOT NULL,
    adjustment_date date NOT NULL,
    confirmed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_adjustments_settlement_id ON public.settlement_adjustments (settlement_id);

CREATE TABLE IF NOT EXISTS public.settlement_index_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint NOT NULL,
    operation varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    retry_count integer NOT NULL,
    max_retries integer NOT NULL,
    error_message text,
    next_retry_at timestamp(6),
    processed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_settlement_index_queue_status ON public.settlement_index_queue (status);

CREATE TABLE IF NOT EXISTS public.payouts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint,
    seller_id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    bank_code varchar(10) NOT NULL,
    bank_account_number varchar(50) NOT NULL,
    account_holder_name varchar(100) NOT NULL,
    status varchar(20) NOT NULL,
    firm_banking_transaction_id varchar(100),
    failure_reason text,
    retry_count integer NOT NULL,
    operator_id varchar(100),
    version bigint NOT NULL,
    requested_at timestamp(6) NOT NULL,
    sent_at timestamp(6),
    completed_at timestamp(6),
    failed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payouts_settlement ON public.payouts (settlement_id) WHERE settlement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payouts_status ON public.payouts (status, requested_at);

CREATE TABLE IF NOT EXISTS public.chargebacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL,
    settlement_id bigint,
    amount numeric(10,2) NOT NULL,
    reason_code varchar(50) NOT NULL,
    reason_detail text,
    status varchar(20) NOT NULL,
    source varchar(20) NOT NULL,
    pg_chargeback_id varchar(128),
    decided_by varchar(255),
    decision_note text,
    raised_at timestamp(6) NOT NULL,
    decided_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_chargebacks_pg_id_unique ON public.chargebacks (pg_chargeback_id) WHERE pg_chargeback_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_chargebacks_status_raised ON public.chargebacks (status, raised_at DESC);

CREATE TABLE IF NOT EXISTS public.ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_id bigint NOT NULL,
    reference_type varchar(30) NOT NULL,
    entry_type varchar(50) NOT NULL,
    debit_account varchar(50) NOT NULL,
    credit_account varchar(50) NOT NULL,
    amount numeric(14,2) NOT NULL,
    status varchar(20) NOT NULL,
    settlement_date date NOT NULL,
    posted_at timestamp(6),
    memo varchar(500),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ledger_reference ON public.ledger_entries (reference_id, reference_type);
CREATE INDEX IF NOT EXISTS idx_ledger_status ON public.ledger_entries (status);

CREATE TABLE IF NOT EXISTS public.ledger_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type varchar(30) NOT NULL,
    settlement_id bigint NOT NULL,
    refund_id bigint,
    refund_amount numeric(14,2),
    adjustment_date date,
    status varchar(20) NOT NULL,
    retry_count integer NOT NULL,
    last_error text,
    created_at timestamp(6) NOT NULL,
    processed_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_ledger_outbox_poll ON public.ledger_outbox (status, id);

CREATE TABLE IF NOT EXISTS public.pg_reconciliation_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_provider varchar(20) NOT NULL,
    target_date date NOT NULL,
    file_name varchar(255) NOT NULL,
    status varchar(20) NOT NULL,
    started_at timestamp(6) NOT NULL,
    finished_at timestamp(6),
    total_pg_rows integer NOT NULL,
    total_internal_rows integer NOT NULL,
    matched_count integer NOT NULL,
    discrepancy_count integer NOT NULL,
    auto_corrected_count integer NOT NULL,
    operator_id varchar(100),
    note text
);
CREATE INDEX IF NOT EXISTS idx_pg_reconciliation_runs_target_date ON public.pg_reconciliation_runs (target_date DESC);

CREATE TABLE IF NOT EXISTS public.pg_reconciliation_discrepancies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL,
    type varchar(30) NOT NULL,
    payment_id bigint,
    pg_transaction_id varchar(500),
    internal_amount numeric(12,2),
    pg_amount numeric(12,2),
    difference numeric(12,2),
    status varchar(20) NOT NULL,
    resolved_at timestamp(6),
    resolved_by varchar(100),
    note text,
    created_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pg_recon_discrepancy_run ON public.pg_reconciliation_discrepancies (run_id, status);

CREATE TABLE IF NOT EXISTS public.settlement_loan_deductions (
    settlement_id bigint PRIMARY KEY,
    seller_id bigint NOT NULL,
    deducted numeric(19,2) NOT NULL,
    created_at timestamp(6) NOT NULL
);

-- ── 이벤트 인프라 (settlement 가 SettlementCreated 발행 + payment/order/user/product 소비) ──
CREATE TABLE IF NOT EXISTS public.outbox_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type varchar(50) NOT NULL,
    aggregate_id varchar(64) NOT NULL,
    event_type varchar(100) NOT NULL,
    event_id uuid NOT NULL UNIQUE,
    trace_parent varchar(64),
    payload jsonb NOT NULL,
    status varchar(20) NOT NULL,
    retry_count integer NOT NULL,
    last_error text,
    created_at timestamp(6) NOT NULL,
    published_at timestamp(6)
);
CREATE INDEX IF NOT EXISTS idx_outbox_status_created ON public.outbox_events (status, created_at);

CREATE TABLE IF NOT EXISTS public.processed_events (
    consumer_group varchar(100) NOT NULL,
    event_id uuid NOT NULL,
    event_type varchar(100) NOT NULL,
    processed_at timestamp(6) NOT NULL,
    PRIMARY KEY (consumer_group, event_id)
);

-- ── CQRS 로컬 프로젝션 (order 이벤트로 적재 — Phase 2/3b) ──
CREATE TABLE IF NOT EXISTS public.settlement_payment_view (
    payment_id bigint PRIMARY KEY,
    order_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    status varchar(20) NOT NULL,
    captured_at timestamp(6),
    seller_id bigint,
    seller_tier varchar(20),
    settlement_cycle varchar(20),
    payment_method varchar(40),
    refunded_amount numeric(15,2),
    pg_transaction_id varchar(100),
    updated_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_settlement_payment_view_captured ON public.settlement_payment_view (captured_at, status);

CREATE TABLE IF NOT EXISTS public.settlement_order_view (
    order_id bigint PRIMARY KEY,
    user_id bigint NOT NULL,
    product_id bigint,
    status varchar(40),
    amount numeric(15,2),
    created_at timestamp(6),
    updated_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_settlement_order_view_user ON public.settlement_order_view (user_id);

CREATE TABLE IF NOT EXISTS public.settlement_user_view (
    user_id bigint PRIMARY KEY,
    email varchar(255),
    updated_at timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settlement_product_view (
    product_id bigint PRIMARY KEY,
    name varchar(255),
    updated_at timestamp(6) NOT NULL
);

-- 감사 로그 (shared-common audit)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint,
    actor_email varchar(255),
    action varchar(50) NOT NULL,
    resource_type varchar(50),
    resource_id varchar(64),
    ip_address varchar(45),
    user_agent varchar(500),
    detail_json jsonb,
    created_at timestamp(6) NOT NULL
);
