-- V20260722160000: 지급후 회수 채권·상계 (seed-p0-6)
--
-- 무엇을: COMPLETED Payout 정산의 차지백·PG 대사 회수분 중 holdback 으로 흡수되지 못한 잔여를
--   채권(seller_recoveries)으로 열고, 후속 정산 확정 시 상계 이력(recovery_allocations)으로만
--   회수한다. COMPLETED Payout·DONE 정산 원본은 불변.
--
-- 멱등 키:
--   채권 발생 = uq_seller_recovery_source_adjustment (조정 1건당 채권 1건)
--   상계     = uq_recovery_allocation_settlement (후속 정산 1건당 채권별 상계 1건)
--   원장     = 기존 uq_ledger_reference_accounts (reference_type 축 분리로 재사용)
--
-- append-only 강제(DB 계층): 채권은 상계 진행 필드(allocated_amount/status/closed_at)만 갱신 허용,
--   상계 이력은 UPDATE/DELETE 전면 금지 — 애플리케이션 버그·수기 SQL 로부터 감사 추적을 보호한다.
--
-- 원장 CHECK 확장: 채권 발생(RECOVERY_RECOGNIZED, Dr AR/Cr AP)·상계(RECOVERY_OFFSET, Dr AP/Cr AR)
--   분개가 CHECK 를 통과하도록 허용값을 넓힌다 (V20260722120000 과 동일한 DROP→ADD NOT VALID→VALIDATE 패턴).
--
-- 롤백 조건(수동): 두 테이블이 비어 있고 신규 reference_type/entry_type 행이 없을 때에 한해
--   테이블·트리거 DROP + CHECK 를 구 허용값으로 복원할 수 있다.

CREATE TABLE public.seller_recoveries (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_adjustment_id bigint        NOT NULL,
    seller_id            bigint        NOT NULL,
    original_amount      numeric(19,2) NOT NULL,
    allocated_amount     numeric(19,2) NOT NULL DEFAULT 0,
    status               varchar(32)   NOT NULL DEFAULT 'OPEN',
    created_at           timestamp     NOT NULL DEFAULT now(),
    closed_at            timestamp,
    CONSTRAINT uq_seller_recovery_source_adjustment UNIQUE (source_adjustment_id),
    CONSTRAINT fk_seller_recovery_adjustment
        FOREIGN KEY (source_adjustment_id) REFERENCES public.settlement_adjustments (id),
    CONSTRAINT chk_seller_recovery_amount    CHECK (original_amount > 0),
    CONSTRAINT chk_seller_recovery_allocated CHECK (allocated_amount >= 0 AND allocated_amount <= original_amount),
    CONSTRAINT chk_seller_recovery_status    CHECK (status IN ('OPEN', 'MANUAL_REQUIRED', 'CLOSED'))
);

-- 상계 스캔 축: 셀러의 OPEN 채권을 오래된 순으로 잠그며 소진한다.
CREATE INDEX idx_seller_recovery_seller_status ON public.seller_recoveries (seller_id, status, id);

-- payout 축 미보관: 상계는 후속 "정산" 단위가 정본이고, 지급은 (settlement_id, payout_type) UNIQUE 로
-- 역추적 가능하다. payout_id 를 두면 payout 생성(상계 이후) 시점에 UPDATE 가 필요해 append-only 와 모순.
CREATE TABLE public.recovery_allocations (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recovery_id   bigint        NOT NULL,
    settlement_id bigint        NOT NULL,
    amount        numeric(19,2) NOT NULL,
    created_at    timestamp     NOT NULL DEFAULT now(),
    CONSTRAINT uq_recovery_allocation_settlement UNIQUE (recovery_id, settlement_id),
    CONSTRAINT fk_recovery_allocation_recovery
        FOREIGN KEY (recovery_id) REFERENCES public.seller_recoveries (id),
    CONSTRAINT fk_recovery_allocation_settlement
        FOREIGN KEY (settlement_id) REFERENCES public.settlements (id),
    CONSTRAINT chk_recovery_allocation_amount CHECK (amount > 0)
);

CREATE INDEX idx_recovery_allocation_settlement ON public.recovery_allocations (settlement_id);

-- append-only 가드: 채권은 불변 필드(출처·셀러·원금·발생시각) 변경과 삭제를 금지한다.
CREATE OR REPLACE FUNCTION public.guard_seller_recovery_history() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'seller_recoveries is append-only: DELETE forbidden (id=%)', OLD.id;
    END IF;
    IF NEW.source_adjustment_id <> OLD.source_adjustment_id
       OR NEW.seller_id <> OLD.seller_id
       OR NEW.original_amount <> OLD.original_amount
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'seller_recoveries immutable fields changed (id=%)', OLD.id;
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_guard_seller_recovery
    BEFORE UPDATE OR DELETE ON public.seller_recoveries
    FOR EACH ROW EXECUTE FUNCTION public.guard_seller_recovery_history();

-- 상계 이력은 전면 불변.
CREATE OR REPLACE FUNCTION public.guard_recovery_allocation_history() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'recovery_allocations is append-only: % forbidden (id=%)', TG_OP, OLD.id;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_guard_recovery_allocation
    BEFORE UPDATE OR DELETE ON public.recovery_allocations
    FOR EACH ROW EXECUTE FUNCTION public.guard_recovery_allocation_history();

-- 원장 CHECK 확장 — 채권 발생·상계 분개 허용.
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_ref_type;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_ref_type
        CHECK (reference_type IN ('SETTLEMENT', 'REFUND', 'CHARGEBACK', 'PG_RECONCILIATION',
                                  'SELLER_RECOVERY', 'RECOVERY_OFFSET')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_ref_type;

ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_entry_type;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_entry_type
        CHECK (entry_type IN ('SETTLEMENT_CREATED', 'SETTLEMENT_CONFIRMED', 'REFUND_REVERSED',
                              'CHARGEBACK_REVERSED', 'RECON_REVERSED',
                              'COMMISSION_RECOGNIZED', 'PAYOUT_EXECUTED',
                              'RECOVERY_RECOGNIZED', 'RECOVERY_OFFSET')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_entry_type;
