-- V20260723100100: 송금 반송(bounce) 레코드 (Seed D1 Part B)
--
-- 무엇을: COMPLETED 송금이 은행단에서 계좌 문제로 되돌아온 사후 사건을 기록한다. 펌뱅킹 호출 실패
--   (SENDING→FAILED→retry)와 달리, 반송은 자금 이동이 COMPLETED 로 종결된 뒤 발생하므로 원 payout 을
--   변경하지 않고(P0-6 선례) 별도 레코드로만 표현한다. 정정 계좌로 신규 payout 을 재발행해 그 id 를
--   resolved_payout_id 로 링크한다.
--
-- 멱등: payout_id UNIQUE 가 "반송당 정확히 한 번"을 DB 로 강제한다 — 같은 송금을 두 번 반송해도 bounce 는
--   1건, 재지급도 1건(이중지급 차단). resolved_payout_id 는 재발행 payout 링크(set-once, NULL 허용:
--   기록 직후~재발행 사이 짧은 창).
--
-- FK: payout_id → payouts(id)(반송된 원 송금). resolved_payout_id → payouts(id)(재발행 송금,
--   settlement_id=NULL 인 수동성 payout — 원 COMPLETED 가 (settlement_id, payout_type) 부분 UNIQUE
--   슬롯을 점유하므로 재발행은 그 슬롯을 피한다. 정산 링크는 payout_id→원 payout→settlement_id 로 역추적).
--
-- 원장(GL): 손대지 않는다. payout 의 cash-outflow GL 인식이 ADR 0026 대기라 payout→원장 전표 자체가
--   아직 없다 → 반송 역분개도 ADR 0026 후속 범위. 이 마이그레이션은 ledger_entries CHECK 를 건드리지 않는다.

CREATE TABLE public.payout_bounces (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_id          bigint       NOT NULL,
    reason             text         NOT NULL,
    resolved_payout_id bigint,
    operator_id        varchar(100),
    bounced_at         timestamp    NOT NULL DEFAULT now(),
    created_at         timestamp    NOT NULL DEFAULT now(),
    CONSTRAINT uq_payout_bounce_payout UNIQUE (payout_id),
    CONSTRAINT fk_payout_bounce_payout
        FOREIGN KEY (payout_id) REFERENCES public.payouts (id),
    CONSTRAINT fk_payout_bounce_resolved
        FOREIGN KEY (resolved_payout_id) REFERENCES public.payouts (id)
);

-- resolved payout 역방향 조회(재발행 payout → 어떤 반송에서 나왔나) + FK 자식 인덱스.
CREATE INDEX idx_payout_bounce_resolved ON public.payout_bounces (resolved_payout_id);

COMMENT ON TABLE public.payout_bounces IS '송금 반송 기록 — 완료 송금의 은행 되돌림 + 정정계좌 재지급 링크 (Seed D1).';
COMMENT ON CONSTRAINT uq_payout_bounce_payout ON public.payout_bounces IS '반송당 1건 — 이중 재지급 차단 멱등 관문.';
