-- 정보계 월마감 (TIS 마트) — 셀러 월 정산 집계 마트 + 마감 run 감사.
--
-- monthly_closing_runs: 월마감 실행 감사 단위(기간당 최신 1행 upsert).
--   COMPLETED 시 합계 스냅샷(total_*)과 품질 카운트(unmapped/pending)를 못박고,
--   FAILED 시 failure_reason 만 남는다(마트는 건드리지 않음).
-- seller_monthly_closings: 기간 × 셀러 마트 행 — DONE 정산만 집계한 확정 실적.
--   재마감은 기간 단위 전체 교체(delete+insert)로 멱등. 원장 마감(ledger_periods CLOSED)된
--   기간의 재적재는 애플리케이션(MonthlyClosingLockedException)이 거부한다.
CREATE TABLE IF NOT EXISTS public.monthly_closing_runs (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_ym        varchar(7) NOT NULL,
    status           varchar(20) NOT NULL,
    triggered_by     varchar(100) NOT NULL,
    started_at       timestamptz(6) NOT NULL,
    finished_at      timestamptz(6),
    seller_count     integer NOT NULL DEFAULT 0,
    settlement_count bigint NOT NULL DEFAULT 0,
    unmapped_count   bigint NOT NULL DEFAULT 0,
    pending_count    bigint NOT NULL DEFAULT 0,
    total_gross      numeric(18,2),
    total_refunded   numeric(18,2),
    total_commission numeric(18,2),
    total_holdback   numeric(18,2),
    total_net        numeric(18,2),
    failure_reason   varchar(500),
    created_at       timestamptz(6) NOT NULL,
    CONSTRAINT uq_monthly_closing_runs_ym UNIQUE (period_ym),
    CONSTRAINT chk_monthly_closing_run_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_monthly_closing_run_ym CHECK (period_ym ~ '^[0-9]{4}-[0-9]{2}$')
);

CREATE TABLE IF NOT EXISTS public.seller_monthly_closings (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_ym         varchar(7) NOT NULL,
    seller_id         bigint NOT NULL,
    settlement_count  bigint NOT NULL,
    gross_amount      numeric(18,2) NOT NULL,
    refunded_amount   numeric(18,2) NOT NULL,
    commission_amount numeric(18,2) NOT NULL,
    holdback_amount   numeric(18,2) NOT NULL,
    net_amount        numeric(18,2) NOT NULL,
    created_at        timestamptz(6) NOT NULL,
    CONSTRAINT uq_seller_monthly_closings UNIQUE (period_ym, seller_id),
    CONSTRAINT chk_seller_monthly_closing_ym CHECK (period_ym ~ '^[0-9]{4}-[0-9]{2}$')
);

-- 셀러 축 조회(셀러별 월 추이) 가속 — 기간 축은 uq_seller_monthly_closings 선두 컬럼이 커버.
CREATE INDEX IF NOT EXISTS idx_seller_monthly_closings_seller
    ON public.seller_monthly_closings (seller_id, period_ym);
