-- A1 Phase 5 — settlement 자체 원장 월마감·기간잠금·확정 시산표 스냅샷.
--
-- ledger_periods: 원장 회계 기간(월) 단위. 행이 없으면 암묵적 OPEN, CLOSED 행이 있으면 마감된 기간이다.
-- 마감 시 그 시점의 확정 시산표 차변·대변 합계를 total_debit/total_credit 에 스냅샷으로 못박고,
-- closed_by/closed_at 이 감사 이력을 남긴다. append-then-close 모델 — 재개봉(reopen) 전이는 없다.
CREATE TABLE IF NOT EXISTS public.ledger_periods (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_ym    varchar(7) NOT NULL,
    status       varchar(20) NOT NULL,
    closed_at    timestamp(6),
    closed_by    varchar(100),
    total_debit  numeric(18,2),
    total_credit numeric(18,2),
    created_at   timestamp(6) NOT NULL,
    CONSTRAINT uq_ledger_periods_ym UNIQUE (period_ym),
    CONSTRAINT chk_ledger_period_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT chk_ledger_period_ym CHECK (period_ym ~ '^[0-9]{4}-[0-9]{2}$')
);

-- 마감 기간 조회(잠금 가드 isClosed) 가속 — status 로 필터하는 period_ym 조회.
CREATE INDEX IF NOT EXISTS idx_ledger_periods_status ON public.ledger_periods (status, period_ym);
