-- V20260811120000: 세금계산서 스캔(AI OCR) 원장 — 수취 스캔본을 읽어 발행분과 대사한다.
--
-- 무엇을:
--   tax_invoice_scans — 셀러가 올린 세금계산서 스캔본 1건의 OCR 추출 결과 + 대사 상태.
--   기존 tax_invoices(플랫폼→셀러 발행분)의 "반대편" — 발행이 아니라 수취 증빙을 읽어 대조하는 쪽이다.
--
-- 멱등/정본:
--   (seller_id, file_hash) UNIQUE = 멱등 키. 같은 셀러가 같은 파일을 다시 올려도 새 행이 생기지 않고,
--   AI OCR 재호출도 이 키에서 차단된다(호출 비용 + 같은 파일이 다른 결과로 두 번 저장되는 것 방지).
--
-- 상태:
--   EXTRACTED → MATCHED | MISMATCHED | UNMATCHED | REJECTED, MISMATCHED/UNMATCHED → MATCHED | REJECTED.
--   MATCHED·REJECTED 는 종결(애플리케이션 상태머신이 강제). MATCHED 면 linked_tax_invoice_id 가 반드시 있다.
--
-- PII: 사업자등록번호는 앱단 AES-GCM(enc:v1, PayoutFieldEncryptionConverter)로 암호화해 *_enc 에 저장한다
--   — seller_tax_profiles.business_reg_no_enc 와 동일 스킴·동일 키(PAYOUT_ENC_KEY). API 응답은 마스킹만 나간다.
--
-- 시각: N1(DATA-STANDARD) — 순간은 UTC tz-aware(timestamptz), 작성일자는 달력일(date)이다.
--
-- 롤백 조건(수동): 테이블이 비어 있을 때에 한해 DROP 가능(다른 테이블이 참조하지 않는다).

CREATE TABLE IF NOT EXISTS public.tax_invoice_scans (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id              bigint        NOT NULL,
    file_name              varchar(255)  NOT NULL,
    content_type           varchar(100)  NOT NULL,
    file_hash              varchar(64)   NOT NULL,
    size_bytes             bigint        NOT NULL,
    status                 varchar(20)   NOT NULL,
    supplier_business_no_enc text,
    buyer_business_no_enc    text,
    written_date           date          NOT NULL,
    supply_amount          numeric(19,2) NOT NULL,
    tax_amount             numeric(19,2) NOT NULL,
    total_amount           numeric(19,2) NOT NULL,
    approval_number        varchar(64),
    confidence             numeric(4,3)  NOT NULL,
    ocr_model              varchar(64)   NOT NULL,
    linked_tax_invoice_id  bigint,
    review_note            varchar(500),
    created_at             timestamptz(6) NOT NULL,
    updated_at             timestamptz(6) NOT NULL,
    CONSTRAINT uq_tax_invoice_scan_seller_file UNIQUE (seller_id, file_hash),
    CONSTRAINT fk_tax_invoice_scan_invoice FOREIGN KEY (linked_tax_invoice_id)
        REFERENCES public.tax_invoices (id),
    CONSTRAINT chk_tax_invoice_scan_status
        CHECK (status IN ('EXTRACTED', 'MATCHED', 'MISMATCHED', 'UNMATCHED', 'REJECTED')),
    CONSTRAINT chk_tax_invoice_scan_amounts
        CHECK (supply_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0),
    CONSTRAINT chk_tax_invoice_scan_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT chk_tax_invoice_scan_size CHECK (size_bytes > 0),
    -- 확정 대사(MATCHED)는 반드시 발행분을 가리킨다. 그 밖의 상태는 후보를 가리키거나(MISMATCHED) 비운다.
    CONSTRAINT chk_tax_invoice_scan_matched_link
        CHECK (status <> 'MATCHED' OR linked_tax_invoice_id IS NOT NULL)
);

COMMENT ON TABLE public.tax_invoice_scans IS
    '세금계산서 스캔 OCR 추출·대사 원장 — (seller_id, file_hash) 멱등, 사업자번호는 앱단 암호화.';
COMMENT ON COLUMN public.tax_invoice_scans.file_hash IS 'SHA-256(파일 바이트) hex 64자 — 멱등 키이자 재업로드 판정 근거.';
COMMENT ON COLUMN public.tax_invoice_scans.confidence IS 'OCR 신뢰도 0~1. 결정적 텍스트 파서는 1.000, LLM 은 모델 보고값.';
COMMENT ON COLUMN public.tax_invoice_scans.linked_tax_invoice_id IS 'MATCHED 면 확정 대사 대상, MISMATCHED 면 조사용 후보.';

-- 관리자 리뷰 큐(상태별 최신순) 가속.
CREATE INDEX IF NOT EXISTS idx_tax_invoice_scans_status ON public.tax_invoice_scans (status, id DESC);
-- 셀러 축 조회.
CREATE INDEX IF NOT EXISTS idx_tax_invoice_scans_seller ON public.tax_invoice_scans (seller_id, id DESC);
