-- V20260715130000: audit_logs 월별 RANGE 파티셔닝 전환 (확장성 축 보강)
--
-- [왜 파티셔닝인가]
--   audit_logs 는 append-only 감사 테이블이라 무한 증가한다. 단일 힙은 최근-구간 조회 지연과
--   대량 DELETE 리텐션의 블로트를 유발한다. 월별 파티션은 파티션 프루닝으로 최근 구간만 스캔하고,
--   리텐션을 DETACH+DROP(메타데이터 연산)으로 처리한다.
-- [왜 created_at 키인가]
--   감사 조회·리텐션이 모두 시간 축이라 created_at 이 유일 유효 키다. PK 를 (id, created_at) 복합으로
--   두어 파티션 키를 PK 에 포함하면서 id 전역 유일성을 유지한다. 엔티티 @GeneratedValue(IDENTITY) 와의
--   호환을 위해 신규 부모도 GENERATED BY DEFAULT AS IDENTITY 로 두고(INSERT ... RETURNING id 동작),
--   구 identity 를 DROP 해 시퀀스 이름을 비운 뒤 max(id) 로 setval 하여 id 연속성을 보존한다.
--   컬럼 이름·타입·순서·NULL 은 베이스라인 V1 과 완전 동일(ip_address·user_agent·detail_json 순) — validate 통과.
-- [리텐션 정책]
--   금융 감사 로그는 장기 보관 원칙 — 기본 보존은 운영 정책에 위임하고 도구만 제공:
--   prune_audit_logs(retain_months)=DETACH+DROP(DEFAULT 보호), ensure_audit_log_partition(months_ahead)=선생성.
-- 기준 스키마: settlement_db 베이스라인 V1__settlement_baseline.sql (public, GENERATED BY DEFAULT AS IDENTITY).
-- 인덱스 3종은 이번에 표준으로 신규 추가.

-- 1) 기존 테이블·PK·identity 정리 (이름 충돌 회피). identity DROP 으로 audit_logs_id_seq 이름을 비운다.
ALTER TABLE audit_logs RENAME TO audit_logs_old;
ALTER TABLE audit_logs_old RENAME CONSTRAINT audit_logs_pkey TO audit_logs_old_pkey;
ALTER TABLE audit_logs_old ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- 2) 파티션드 부모 — 컬럼 구성 베이스라인과 동일, PK 만 (id, created_at).
CREATE TABLE audit_logs (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    actor_id      bigint,
    actor_email   varchar(255),
    action        varchar(50)  NOT NULL,
    resource_type varchar(50),
    resource_id   varchar(64),
    ip_address    varchar(45),
    user_agent    varchar(500),
    detail_json   jsonb,
    created_at    timestamp(6) NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- 3) 월별 파티션 2026_01 ~ 2027_06 + DEFAULT
CREATE TABLE audit_logs_2026_01 PARTITION OF audit_logs FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE audit_logs_2026_02 PARTITION OF audit_logs FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE audit_logs_2026_03 PARTITION OF audit_logs FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE audit_logs_2026_04 PARTITION OF audit_logs FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE audit_logs_2026_05 PARTITION OF audit_logs FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE audit_logs_2026_06 PARTITION OF audit_logs FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE audit_logs_2026_07 PARTITION OF audit_logs FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE audit_logs_2026_08 PARTITION OF audit_logs FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE audit_logs_2026_09 PARTITION OF audit_logs FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE audit_logs_2026_10 PARTITION OF audit_logs FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE audit_logs_2026_11 PARTITION OF audit_logs FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE audit_logs_2026_12 PARTITION OF audit_logs FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE audit_logs_2027_01 PARTITION OF audit_logs FOR VALUES FROM ('2027-01-01') TO ('2027-02-01');
CREATE TABLE audit_logs_2027_02 PARTITION OF audit_logs FOR VALUES FROM ('2027-02-01') TO ('2027-03-01');
CREATE TABLE audit_logs_2027_03 PARTITION OF audit_logs FOR VALUES FROM ('2027-03-01') TO ('2027-04-01');
CREATE TABLE audit_logs_2027_04 PARTITION OF audit_logs FOR VALUES FROM ('2027-04-01') TO ('2027-05-01');
CREATE TABLE audit_logs_2027_05 PARTITION OF audit_logs FOR VALUES FROM ('2027-05-01') TO ('2027-06-01');
CREATE TABLE audit_logs_2027_06 PARTITION OF audit_logs FOR VALUES FROM ('2027-06-01') TO ('2027-07-01');
CREATE TABLE audit_logs_default  PARTITION OF audit_logs DEFAULT;

-- 4) 데이터 이관 (GENERATED BY DEFAULT 라 명시 id 삽입 허용) 후 시퀀스를 max(id) 로 재개.
INSERT INTO audit_logs
    (id, actor_id, actor_email, action, resource_type, resource_id, ip_address, user_agent, detail_json, created_at)
SELECT id, actor_id, actor_email, action, resource_type, resource_id, ip_address, user_agent, detail_json, created_at
FROM audit_logs_old;
DO $$
DECLARE mx bigint; has boolean;
BEGIN
    SELECT COALESCE(MAX(id), 0), COUNT(*) > 0 INTO mx, has FROM audit_logs;
    PERFORM setval(pg_get_serial_sequence('audit_logs', 'id'), GREATEST(mx, 1), has);
END $$;
DROP TABLE audit_logs_old;

-- 5) 인덱스 표준 3종 신규 생성 (베이스라인엔 없었음 — 전 서비스 표준화)
CREATE INDEX idx_audit_logs_actor_time  ON audit_logs (actor_id, created_at DESC);
CREATE INDEX idx_audit_logs_resource    ON audit_logs (resource_type, resource_id, created_at DESC);
CREATE INDEX idx_audit_logs_action_time ON audit_logs (action, created_at DESC);

-- 6) append-only 강제 (UPDATE·DELETE 거부) — 파티션드 부모 BEFORE ROW 트리거는 신규 파티션에도 자동 적용
CREATE OR REPLACE FUNCTION audit_logs_block_modify()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs 는 append-only 입니다: % 연산 불가 (감사 로그 변조 차단)', TG_OP;
END;
$$;
CREATE TRIGGER trg_audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_block_modify();

-- 7) 유지보수 함수 (전 서비스 동일 시그니처)
CREATE OR REPLACE FUNCTION ensure_audit_log_partition(months_ahead int DEFAULT 1)
RETURNS int
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
DECLARE
    i int;
    start_month date;
    end_month date;
    part_name text;
    created int := 0;
BEGIN
    FOR i IN 0..months_ahead LOOP
        start_month := date_trunc('month', CURRENT_DATE + make_interval(months => i))::date;
        end_month   := (start_month + interval '1 month')::date;
        part_name   := 'audit_logs_' || to_char(start_month, 'YYYY_MM');
        IF to_regclass(part_name) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF audit_logs FOR VALUES FROM (%L) TO (%L)',
                part_name, start_month, end_month);
            created := created + 1;
        END IF;
    END LOOP;
    RETURN created;
END;
$$;

CREATE OR REPLACE FUNCTION prune_audit_logs(retain_months int)
RETURNS int
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
DECLARE
    cutoff date;
    r record;
    dropped int := 0;
BEGIN
    IF retain_months < 1 THEN
        RAISE EXCEPTION 'retain_months 는 1 이상이어야 합니다 (요청: %)', retain_months;
    END IF;
    cutoff := (date_trunc('month', CURRENT_DATE) - make_interval(months => retain_months))::date;
    FOR r IN
        SELECT c.relname AS part_name
        FROM pg_inherits inh
        JOIN pg_class c ON c.oid = inh.inhrelid
        JOIN pg_class p ON p.oid = inh.inhparent
        WHERE p.relname = 'audit_logs'
          AND c.relname ~ '^audit_logs_[0-9]{4}_[0-9]{2}$'
    LOOP
        IF to_date(right(r.part_name, 7), 'YYYY_MM') < cutoff THEN
            EXECUTE format('ALTER TABLE audit_logs DETACH PARTITION %I', r.part_name);
            EXECUTE format('DROP TABLE %I', r.part_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;
    RETURN dropped;
END;
$$;

COMMENT ON TABLE audit_logs IS '민감 작업 감사 추적. created_at 월별 RANGE 파티션 + append-only 트리거. 선생성=ensure_audit_log_partition, 리텐션=prune_audit_logs(DETACH+DROP, DEFAULT 보호).';
