-- V20260723160000: 정산 연계 세무 산출물 (Seed B2, ADR 0029, 2026-07-24 정정 반영)
--
-- 무엇을:
--   1) seller_tax_profiles  — 셀러 세무유형(개인/사업자)·사업자등록번호 레지스트리(관리자 upsert).
--      원천징수 판단 입력을 신규 프로젝션 없이 settlement 자체에서 확보(payout 계좌 레지스트리와 동형).
--   2) tax_invoices         — 플랫폼→셀러 수수료 세금계산서(포함과세: 공급가액=commission−vat, 세액=vat,
--      합계=commission). 발행번호·정산 UNIQUE 로 멱등.
--   3) 원장 CHECK 확장       — 세무 전표(부가세 예수 Dr COMMISSION_REVENUE/Cr VAT_PAYABLE, 포함과세)가
--      CHECK 를 통과하도록 계정·reference_type·entry_type 허용값을 넓힌다(기존 DROP→ADD NOT VALID→VALIDATE 패턴).
--      원천징수는 이 원장에 없다(실지급 통합 — account-service GL WITHHOLDING_PAYABLE 로 이관, ADR 0026 확장).
--
-- 멱등/정본:
--   세무유형 = seller_id PK(셀러당 1행 = upsert, 가변 원천이므로 UPDATE 허용 — payouts/ledger 불변 대상 아님).
--   세금계산서 = settlement_id UNIQUE + issue_number UNIQUE(정산 1건당 계산서 1건).
--   세무 전표 = 기존 uq_ledger_reference_accounts(reference_type 축 SETTLEMENT_TAX 로 분리 재사용).
--
-- PII: 사업자등록번호는 앱단 AES-GCM(enc:v1, PayoutFieldEncryptionConverter) 로 암호화해 business_reg_no_enc(text)
--   에 저장한다 — Payout 지급계좌 암호화와 동일 스킴·동일 키(PAYOUT_ENC_KEY). 개인 셀러는 미보유(NULL).
--
-- 롤백 조건(수동): 두 신규 테이블이 비어 있고 SETTLEMENT_TAX/세무 entry_type 원장 행이 없을 때에 한해
--   테이블 DROP + CHECK 를 구 허용값으로 복원할 수 있다.

CREATE TABLE public.seller_tax_profiles (
    seller_id          bigint      PRIMARY KEY,
    tax_type           varchar(16) NOT NULL,
    business_reg_no_enc text,
    updated_at         timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT chk_seller_tax_type CHECK (tax_type IN ('INDIVIDUAL', 'BUSINESS'))
);

COMMENT ON TABLE public.seller_tax_profiles IS '셀러 세무유형 레지스트리 — 원천징수 판단 입력의 원천 (Seed B2, ADR 0029).';
COMMENT ON COLUMN public.seller_tax_profiles.business_reg_no_enc IS '사업자등록번호 AES-GCM enc:v1 암호문(앱단), 개인 셀러는 NULL.';

CREATE TABLE public.tax_invoices (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint        NOT NULL,
    seller_id     bigint        NOT NULL,
    supply_amount numeric(19,2) NOT NULL,
    tax_amount    numeric(19,2) NOT NULL,
    total_amount  numeric(19,2) NOT NULL,
    issue_date    date          NOT NULL,
    issue_number  varchar(40)   NOT NULL,
    created_at    timestamp     NOT NULL DEFAULT now(),
    CONSTRAINT uq_tax_invoice_settlement UNIQUE (settlement_id),
    CONSTRAINT uq_tax_invoice_number     UNIQUE (issue_number),
    CONSTRAINT fk_tax_invoice_settlement FOREIGN KEY (settlement_id) REFERENCES public.settlements (id),
    CONSTRAINT chk_tax_invoice_supply CHECK (supply_amount >= 0),
    CONSTRAINT chk_tax_invoice_tax    CHECK (tax_amount >= 0),
    CONSTRAINT chk_tax_invoice_total  CHECK (total_amount = supply_amount + tax_amount)
);

COMMENT ON TABLE public.tax_invoices IS '플랫폼→셀러 수수료 세금계산서 — 공급가액=수수료, 세액=부가세 (Seed B2, ADR 0029).';

CREATE INDEX idx_tax_invoice_seller ON public.tax_invoices (seller_id, id);

-- 원장 CHECK 확장 — 세무 전표 계정·reference_type·entry_type 허용(부가세만 — 원천징수는 account GL 로 이관).
ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_debit_account;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_debit_account
        CHECK (debit_account IN ('ACCOUNTS_RECEIVABLE','ACCOUNTS_PAYABLE','REVENUE','COMMISSION_REVENUE',
                                 'COMMISSION_EXPENSE','SALES_REFUND','CASH',
                                 'VAT_PAYABLE')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_debit_account;

ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_credit_account;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_credit_account
        CHECK (credit_account IN ('ACCOUNTS_RECEIVABLE','ACCOUNTS_PAYABLE','REVENUE','COMMISSION_REVENUE',
                                  'COMMISSION_EXPENSE','SALES_REFUND','CASH',
                                  'VAT_PAYABLE')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_credit_account;

ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_ref_type;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_ref_type
        CHECK (reference_type IN ('SETTLEMENT','REFUND','CHARGEBACK','PG_RECONCILIATION',
                                  'SELLER_RECOVERY','RECOVERY_OFFSET','SETTLEMENT_TAX')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_ref_type;

ALTER TABLE public.ledger_entries DROP CONSTRAINT IF EXISTS chk_ledger_entry_type;
ALTER TABLE public.ledger_entries
    ADD CONSTRAINT chk_ledger_entry_type
        CHECK (entry_type IN ('SETTLEMENT_CREATED','SETTLEMENT_CONFIRMED','REFUND_REVERSED',
                              'CHARGEBACK_REVERSED','RECON_REVERSED',
                              'COMMISSION_RECOGNIZED','PAYOUT_EXECUTED',
                              'RECOVERY_RECOGNIZED','RECOVERY_OFFSET',
                              'VAT_ACCRUED')) NOT VALID;
ALTER TABLE public.ledger_entries VALIDATE CONSTRAINT chk_ledger_entry_type;
