CREATE SCHEMA IF NOT EXISTS education;

CREATE TABLE education.education_courses (
    id UUID PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT education_courses_status_ck CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN', 'CLOSED'))
);

CREATE TABLE education.education_lessons (
    id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES education.education_courses(id),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    sequence INTEGER NOT NULL,
    content_type VARCHAR(30) NOT NULL,
    content_ref TEXT NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT education_lessons_sequence_uk UNIQUE (course_id, sequence),
    CONSTRAINT education_lessons_status_ck CHECK (status IN ('ACTIVE', 'HIDDEN'))
);

CREATE INDEX education_courses_status_idx ON education.education_courses(status, updated_at DESC);
CREATE INDEX education_lessons_course_idx ON education.education_lessons(course_id, sequence);

CREATE TABLE education.outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_id UUID NOT NULL UNIQUE,
    trace_parent VARCHAR(64),
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL,
    last_error TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    published_at TIMESTAMP(6),
    occurred_at TIMESTAMPTZ NOT NULL,
    event_version INTEGER NOT NULL DEFAULT 1,
    producer VARCHAR(64),
    claimed_at TIMESTAMP(6),
    claimed_by VARCHAR(100)
);
CREATE INDEX education_outbox_status_created_idx ON education.outbox_events(status, created_at);

CREATE TABLE education.education_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id UUID NOT NULL,
    actor VARCHAR(100) NOT NULL,
    detail VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX education_audit_resource_idx ON education.education_audit_logs(resource_type, resource_id, created_at DESC);
