-- V4: 보험 PII fail-closed, 소비 이벤트 durable quarantine, 감사 유지보수 함수 권한 강화.

-- 평문 PII가 이미 있으면 제약 추가 전에 명시적으로 중단한다.
-- 데이터 삭제·자동 변환은 하지 않으며, 운영자가 통제된 재암호화 후 migration을 재실행해야 한다.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM insured_person_pii
        WHERE encrypted_rrn NOT LIKE 'enc:v1:%'
    ) THEN
        RAISE EXCEPTION 'V4 중단: insured_person_pii.encrypted_rrn 평문/비지원 암호문 존재';
    END IF;

    IF EXISTS (
        SELECT 1 FROM contractor_pii
        WHERE encrypted_phone NOT LIKE 'enc:v1:%'
    ) THEN
        RAISE EXCEPTION 'V4 중단: contractor_pii.encrypted_phone 평문/비지원 암호문 존재';
    END IF;
END;
$$;

ALTER TABLE insured_person_pii
    ADD CONSTRAINT chk_insured_person_rrn_encrypted
        CHECK (encrypted_rrn LIKE 'enc:v1:%');

ALTER TABLE contractor_pii
    ADD CONSTRAINT chk_contractor_phone_encrypted
        CHECK (encrypted_phone LIKE 'enc:v1:%');

-- event_id 누락/불량 및 payload 계약 위반의 원본 증거. 좌표 UNIQUE로 재전달을 멱등 격리한다.
CREATE TABLE quarantined_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_group  VARCHAR(100) NOT NULL,
    topic           VARCHAR(200) NOT NULL,
    kafka_partition INT          NOT NULL,
    kafka_offset    BIGINT       NOT NULL,
    event_id        UUID,
    cause           VARCHAR(30)  NOT NULL,
    cause_detail    TEXT,
    payload         TEXT,
    occurred_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_insurance_quarantined_record
        UNIQUE (consumer_group, topic, kafka_partition, kafka_offset)
);

CREATE INDEX idx_insurance_quarantined_occurred_at
    ON quarantined_events (occurred_at DESC);

-- PostgreSQL 함수의 기본 PUBLIC EXECUTE를 제거한다. 소유자는 유지보수 실행 권한을 보존한다.
-- 별도 유지보수 역할이 생기면 운영 프로비저닝에서 해당 역할에만 명시적으로 GRANT한다.
REVOKE EXECUTE ON FUNCTION ensure_audit_log_partition(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prune_audit_logs(integer) FROM PUBLIC;
