apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  namespace: lemuel
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
  MANAGEMENT_SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://account-db-service:5432/lemuel_account?reWriteBatchedInserts=true"
  APP_KAFKA_ENABLED: "true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "redpanda:29092"
  JWT_ISSUER: "lemuel-service"
  JWT_TTL_SECONDS: "86400"
