apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: lemuel
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
  ORDER_SERVICE_URI: "http://lemuel-service:8080"
  SETTLEMENT_SERVICE_URI: "http://settlement-service:8080"
  ACCOUNT_SERVICE_URI: "http://account-service:8080"
